name: Update MongoDB Daily

on:
  push:
    branches:
      - user
      - main
  schedule:
    # Run at 7 AM UTC every day
    - cron: '0 7 * * *'

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymongo selenium pandas openpyxl

    - name: Download ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
        wget -N https://chromedriver.storage.googleapis.com/91.0.4472.101/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver_linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Download Google Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get install -y ./google-chrome-stable_current_amd64.deb

    - name: List directory contents
      run: ls -R

    - name: Run update script
      env:
        MONGO_URL: mongodb+srv://leotamen22:FxGkjVn5uBpXPsLL@clustertyep.grmvsbh.mongodb.net/Tyep?retryWrites=true&w=majority
      run: |
        xvfb-run -a python backend/scripts/fnac.py