name: Update MongoDB Daily

on:
  push:
    branches:
      - user
      - main
  schedule:
    # Run at 7 AM UTC every day
    - cron: '0 7 * * *'

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymongo selenium pandas openpyxl

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Download ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
        MAJOR_CHROME_VERSION=$(echo $CHROME_VERSION | cut -d '.' -f 1)
        CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${MAJOR_CHROME_VERSION})
        wget -N https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: List directory contents
      run: ls -R

    - name: Run update script
      env:
        MONGO_URL: mongodb+srv://leotamen22:FxGkjVn5uBpXPsLL@clustertyep.grmvsbh.mongodb.net/Tyep?retryWrites=true&w=majority
      run: |
        xvfb-run -a python backend/scripts/fnac.py
